"""added uuid filed for server

Revision ID: 2d57f570934e
Revises: f091ba748e77
Create Date: 2018-03-23 10:17:00.091009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d57f570934e'
down_revision = 'f091ba748e77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('server', sa.Column('uuid', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_server_uuid'), 'server', ['uuid'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_server_uuid'), table_name='server')
    op.drop_column('server', 'uuid')
    # ### end Alembic commands ###
