"""added active boolean field

Revision ID: 2f8ca3eca3ac
Revises: 2ad182d4797c
Create Date: 2018-03-22 14:15:52.996531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f8ca3eca3ac'
down_revision = '2ad182d4797c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activation', sa.Column('active', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_activation_active'), 'activation', ['active'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_activation_active'), table_name='activation')
    op.drop_column('activation', 'active')
    # ### end Alembic commands ###
