"""preparing to store facts from facter on the DB instead of simply saving the entire json

Revision ID: 86b918b6a8e6
Revises: 2d57f570934e
Create Date: 2018-03-23 15:26:24.034633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86b918b6a8e6'
down_revision = '2d57f570934e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('facter_architecture',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('architecture', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('facter_facts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_virt', sa.Boolean(), nullable=True),
    sa.Column('serialnumber', sa.String(length=128), nullable=True),
    sa.Column('uuid', sa.String(length=128), nullable=True),
    sa.Column('physicalprocessorcount', sa.Integer(), nullable=True),
    sa.Column('processorcount', sa.Integer(), nullable=True),
    sa.Column('memorysize', sa.String(length=32), nullable=True),
    sa.Column('memorysize_mb', sa.String(length=32), nullable=True),
    sa.Column('blockdevice_sda_size', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_facter_facts_is_virt'), 'facter_facts', ['is_virt'], unique=False)
    op.create_table('facter_mac_address',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('macaddress', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('facter_manufacturer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('manufacturer', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('facter_processor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('processor0', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('facter_product_name',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('productname', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('facter_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('facter_version',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('facterversion', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('facter_virtual',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('virtual', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('facter_facts_mac',
    sa.Column('macaddress_id', sa.Integer(), nullable=True),
    sa.Column('facts_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['facts_id'], ['facter_facts.id'], ),
    sa.ForeignKeyConstraint(['macaddress_id'], ['facter_mac_address.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Facter_facts_mac')
    op.drop_table('facter_virtual')
    op.drop_table('facter_version')
    op.drop_table('facter_type')
    op.drop_table('facter_product_name')
    op.drop_table('facter_processor')
    op.drop_table('facter_manufacturer')
    op.drop_table('facter_mac_address')
    op.drop_index(op.f('ix_facter_facts_is_virt'), table_name='facter_facts')
    op.drop_table('facter_facts')
    op.drop_table('facter_architecture')
    # ### end Alembic commands ###
