"""added a field for facter_json

Revision ID: cbe4feb670b5
Revises: fa0aac4468e8
Create Date: 2018-03-29 11:21:16.813866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbe4feb670b5'
down_revision = 'fa0aac4468e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('facter_facts', sa.Column('facter_json', sa.String(length=65536), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('facter_facts', 'facter_json')
    # ### end Alembic commands ###
