"""created and last ping for servers

Revision ID: f091ba748e77
Revises: 2f8ca3eca3ac
Create Date: 2018-03-23 09:32:28.314000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f091ba748e77'
down_revision = '2f8ca3eca3ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('server', sa.Column('created', sa.DateTime(), nullable=True))
    op.add_column('server', sa.Column('last_ping', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_server_created'), 'server', ['created'], unique=False)
    op.create_index(op.f('ix_server_last_ping'), 'server', ['last_ping'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_server_last_ping'), table_name='server')
    op.drop_index(op.f('ix_server_created'), table_name='server')
    op.drop_column('server', 'last_ping')
    op.drop_column('server', 'created')
    # ### end Alembic commands ###
